### ISSUE TITLE
I can't get it to run in windows

### ISSUE THREAD

**Issue by yasserzs3** [kashifulhaque/product-mockup-node-python#2]
As you know you can't run shell scripts directly with windows so i had to use git bash to get it to work but still i can't get the .sh to run properly.

![image](https://github.com/kashifulhaque/product-mockup-node-python/assets/68787298/07a74982-fc4b-48b2-bf84-d1f4b652f604)

**Comment by kashifulhaque** [comment]
This seems like an issue which occurs on Windows. I'd recommend you to open those bash scripts, copy the commands and run them directly from the command line.
Also make sure that you have ImageMagick installed.
