### ISSUE TITLE
convert-im6.q16: unable to open image `artwork.png': No such file or directory @ error/blob.c/OpenBlob/2924. convert-im6.q16: no images defined `tmp.mpc' @ error/convert.c/ConvertImageCommand/3229.

### ISSUE THREAD

**Issue by walidahsan** [kashifulhaque/product-mockup-node-python#3]
Hii my Ubunto terminal is unable to find the Artwork.png...
kindly help me. Thanks

![Screenshot 2023-12-06 140539](https://github.com/kashifulhaque/product-mockup-node-python/assets/80704047/3d975ccd-e894-446e-b0ae-fbf659dd6f10)

**Comment by kashifulhaque** [comment]
Hi, you need to put your template and mask in the `base_images` folder, and not inside `cd base_images`.
Make sure your template is named `template.jpg` and your mask is named `mask.png`.

Once you did that, you will have to run `sh create_maps.sh base_images/template.jpg base_images/mask.png`
(You have to run this command in the `product-mockup-node-python` folder and not inside `product-mockup-node-python/base_images`).

Lastly, you need to run `sh create_mockups.sh`
