### ISSUE TITLE
displaced mockup

### ISSUE THREAD

**Issue by Avni17** [kashifulhaque/product-mockup-node-python#4]
i tried creating mockup but my mockup created was not correct...what do i need to change?
![1060](https://github.com/kashifulhaque/product-mockup-node-python/assets/72393058/252a7e38-455e-4c5e-8179-e726a67f73f4)
![art](https://github.com/kashifulhaque/product-mockup-node-python/assets/72393058/96de93e5-7986-4556-b633-9d446e545003)

![image](https://github.com/kashifulhaque/product-mockup-node-python/assets/72393058/56ad3c00-0465-4029-9f8d-a9f9f2645a5c)

**Comment by kashifulhaque** [comment]
Hi @Avni17 you'll need the tweak the coordinates are per the image. You can use the following diagram as a reference
```
// [0, 0, x1, y1, 0, h, x2, y2, w, h, x3, y3, w, 0, x4, y4]

// x1 = x2
// y1 = y4
// y2 = y3
// x3 = x4
// first w = x4 - x1
// second w = x3 - x2
// first h = y2 - y1
// second h = y3 - y4

//   (x1,y1) --------------------------------(x4,y4)
//           |                              |
//           |                              |
//           |                              |
//           |                              |
//           |                              |
//           |                              |
//           |                              |
//           |                              |
//           |                              |
//   (x2,y2) --------------------------------(x3,y3)
```

**Comment by Avni17** [comment]
alright thanks and i also tried a mockup on a black tshirt but it was quite dull...How do i make it realistic as well as bright?
![WhatsApp Image 2023-12-15 at 00 50 21_f34db8b9](https://github.com/kashifulhaque/product-mockup-node-python/assets/72393058/8db17041-3d86-4bc8-90c7-a57357875aab)
![image](https://github.com/kashifulhaque/product-mockup-node-python/assets/72393058/f42e8d69-f5ec-4587-b1c9-04b2685529f8)

**Comment by kashifulhaque** [comment]
Ooh, that's an interesting case. So far, all the mockups that I did have white (or some shade of white) as the background.
You can try tweaking the `brightness_delta` parameter in the scripts that generate `lighting` and `displacement` map, that should give you a brighter result.

**Comment by Avni17** [comment]
ic...anyways...Thankyou.....

**Comment by kashifulhaque** [comment]
good luck, if you get stuck feel free to ping/raise issue.
