### ISSUE TITLE
INVALID

### ISSUE THREAD

**Issue by hindamosh** [kashifulhaque/product-mockup-node-python#5]
Following the steps and try to work on the available template and mask photos but get INVALID error
 ![invalid_error](https://github.com/kashifulhaque/product-mockup-node-python/assets/39014318/96f12eff-3dc9-4b6f-8520-c09a0d633cd5)

**Comment by kashifulhaque** [comment]
Hi @hindamosh, if the shell script doesn't work, you can copy the command from the shell script and try running it directly and lemme know if you're getting the same error.
