### ISSUE TITLE
Dark colors being distorted

### ISSUE THREAD

**Issue by faiq-fabtechsol** [kashifulhaque/product-mockup-node-python#7]
Hi Brother, thanks for the repo. I am using your repository in one of my projects, For light colors pattern is being transferred quite well but for dark colors color of object is being blurred a little, can you please tell how to solve this issue I have attached one of images that I am experimented on.
here is the input image
![template](https://github.com/kashifulhaque/product-mockup-node-python/assets/141337057/ffc0a2a9-f04c-4650-9ca6-ba30473babda)
here is the mask of input image
![mask](https://github.com/kashifulhaque/product-mockup-node-python/assets/141337057/99898615-19f0-4761-8655-b362f41cf796)
here is the style image
![art11](https://github.com/kashifulhaque/product-mockup-node-python/assets/141337057/3cab9d1d-a5d5-4195-8330-45e1e5dc4422)

and here is the output of this image.
![art11](https://github.com/kashifulhaque/product-mockup-node-python/assets/141337057/acb8de7e-e2a7-4b12-bc9f-18cf6c308b5a)

here you can see texture is not being transfered correctly. I want output like this.
![desired_output](https://github.com/kashifulhaque/product-mockup-node-python/assets/141337057/f02263b2-e4cb-42d2-9c48-d9cc48986121)
thanks in advance.

**Comment by kashifulhaque** [comment]
afaik, ImageMagick expects the mask to be white in colour with transparent background. Can you try this after changing mask colour to white.

Also, you can try changing parameters like scale in [create_swatch_tile.py](https://github.com/kashifulhaque/product-mockup-node-python/blob/main/create_swatch_tile.py) to make the tiling more/less dense.

Lastly, you can also try changing [brightness delta here](https://github.com/kashifulhaque/product-mockup-node-python/blob/main/lighting_map.sh) and in other similar scripts to adjust your output.

It is kind of difficult to create one script that works for everyone, so you just have to fiddle around with the parameters.

**Comment by faiq-fabtechsol** [comment]
@kashifulhaque thanks for you answer after changing the mask to white and decreasing the tiling does some work for me but still output is not as good as it should be. I have also tried with the reshaping the swatches to the size almost equal to the size of object within image but still output is not as accurate.
Now my output is 
![output](https://github.com/kashifulhaque/product-mockup-node-python/assets/141337057/25343c13-b068-4279-bf12-796382913c9e)

you can see here that full pattern is still not being transferred to the output image.

**Comment by faiq-fabtechsol** [comment]
also color of output image is little dull as compared to the swatch

**Comment by nouman-fabtechsol** [comment]
By changing brightness delta, our output does match a lot to the expected output thanks for your help.
