### ISSUE TITLE
unable to open image 'tiled_images/*': No such file or directory

### ISSUE THREAD

**Issue by kension0929** [kashifulhaque/product-mockup-node-python#8]
I just follow the instructions to execute the script: sh create_mockups.sh
But I got follow errors.

convert: unable to open image 'tiled_images/*': No such file or directory @ error/blob.c/OpenBlob/3596.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.
convert: no images defined `mpcs/mockup.mpc' @ error/deprecate.c/ConvertImageCommand/3368.
![dd](https://github.com/user-attachments/assets/da3c3667-0652-41d9-be67-fda8b5bcf697)

Why this could happen?

**Comment by kashifulhaque** [comment]
Hi @kension0929, I forgot to update the README. You might need to run the `create_swatch_tile.py` python script first and then try running the `create_mockups.sh` file.

If that doesn't work, you can try opening the `create_mockups.sh` file in a text editor, like VS Code, and then run the commands individually (except the for loop which iterates over `tiled_images` folder)
